### ISSUE TITLE
[1.19.2 Fabric] The delayed wither death is breaking all mods and datapacks that need to check who killed the wither

### ISSUE THREAD

**Issue by TelepathicGrunt** [MORIMORI0317/BEStyleWither#4]
I received this issue report in 1.19.2 but sounds like all modloaders for all versions of this mod has the issue.
https://github.com/LunaPixelStudios/Medieval-MC/issues/534
https://github.com/TelepathicGrunt/Bumblezone/issues/200

I am the developer of Bumblezone. One of my advancements requires the player to kill the wither with Stinger Spear. However, BE Styled Wither is keeping the Wither alive at 1hp to do the death explosion. This means at the time of the last hit, the Wither is not technically dead which breaks my item's check to see if it killed the Wither in the item's hurt method (I check LivingEntity$isDeadOrDying method on the mob). 

Later, the BE Styled Wither kills the Wither themselves by explosion which makes any mob killed event say the Wither was attached by the Wither itself. So no mod or datapack can ever know who actually killed the wither. This is dangerous implementation that kills mod/datapack compatibility very badly.
![image](https://user-images.githubusercontent.com/40846040/215278707-44db7907-16fd-4054-88ea-492b7a78e0fe.png)

What BE Styled Wither needs to do is to let the Wither actually die when the last hit is delivered. Make sure the isDeadOrDying is now true on that killing blow. Extend the vanilla death timer for the Wither to the duration of this new death animation (while overriding the default vanilla death animation). And then deliver the explosion at the very end of the new death timer properly.

There is nothing I can do on my end to try and be compatible with this mod as even the Fabric Entity Killed events has no info anymore on who killed the Wither due to the delayed death and explosion. Please let me know when you fix this issue. For now, I'm going to have to mark this mod as incompatible with mine to prevent players from being stuck with my very important advancement I use for progression in my mod.

**Comment by MORIMORI0317** [comment]
We could not confirm that the wither was killing itself, but we did confirm that isDeadOrDying was not determining correctly and that the firing of the Fabric kill event was delayed from the time the wither was killed.
Therefore, the process has been changed to use vanilla death animations
https://www.curseforge.com/minecraft/mc-mods/be-style-wither/files/4376609
This should be fixed in this version

**Comment by TelepathicGrunt** [comment]
Yep, tested the 1.19.2 fabric version and my advancement now triggers properly. Thank you!
