### ISSUE TITLE
Wither giving self damage

### ISSUE THREAD

**Issue by peow** [MORIMORI0317/BEStyleWither#6]
When the Wither's double health option is enabled, when the Wither spawns and explodes, it takes damage from the explosion itself, what doesn't happen when this option is disabled
![2024-01-30_23 03 57](https://github.com/MORIMORI0317/BEStyleWither/assets/105888751/b0197f73-234c-48cf-8de5-612ce81168d4)

(spawning)
![2024-01-30_23 06 41](https://github.com/MORIMORI0317/BEStyleWither/assets/105888751/c6625873-2f0f-4fb4-8ce5-c5d774ecfed1)

(explosion)
![2024-01-30_23 06 45](https://github.com/MORIMORI0317/BEStyleWither/assets/105888751/e259a5b1-37f7-47eb-98ec-f8eb797d0e18)

(look at his life)
![2024-01-30_23 06 47](https://github.com/MORIMORI0317/BEStyleWither/assets/105888751/d9417899-7831-4cd4-95a3-4e65388ac378)

-----------------

I pressed F3+ i on the Wither to copy its data, this here is the Wither's data **without** double health

*/summon minecraft:wither -1376.77 -27.59 966.55 {NoGravity: 1b, Brain: {memories: {}}, HurtByTimestamp: 403, Attributes: [{Base: 0.6000000238418579d, Name: "minecraft:generic.movement_speed"}], Invulnerable: 0b, FallFlying: 0b, PortalCooldown: 0, AbsorptionAmount: 0.0f, Invul: 0, FallDistance: 6.380333f, FPower: 0b, DeathTime: 0s, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, BalmData: {}, Motion: [0.08786589638276371d, 0.028543691165005776d, -0.00521039943998736d], **Health: 300.0f**, LeftHanded: 0b, Air: 300s, OnGround: 0b, Rotation: [240.86609f, 0.0f], HandItems: [{}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, HurtTime: 0s}*

---------------

and these are the Wither's data with the option to double health enabled, notice that its health is not at 600.0f, but 420.0f, as it took damage from the explosion itself

*/summon minecraft:wither -1382.50 -32.00 978.50 {Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 0.6000000238418579d, Name: "minecraft:generic.movement_speed"}], Invulnerable: 0b, FallFlying: 0b, PortalCooldown: 0, AbsorptionAmount: 0.0f, Invul: 0, FallDistance: 0.0f, FPower: 0b, DeathTime: 0s, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, BalmData: {}, Motion: [0.0d, -0.0784000015258789d, 0.0d], **Health: 420.0f**, LeftHanded: 0b, Air: 300s, OnGround: 1b, Rotation: [0.0f, 0.0f], HandItems: [{}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, HurtTime: 0s}*

------------

im using Fabric **1.20.1**, Fabric Loader 0.14.22, BE Style Wither v1.6.0

if is possible to fix this please make an update to Fabric 1.20.1 with support to Fabric Loader 0.14.22, thanks

**Comment by MORIMORI0317** [comment]
The problem was that he wasn't taking damage from the explosion, but that his health recovery couldn't keep up with the summoning when he had double health.
We have released a fixed version.
https://modrinth.com/mod/be-style-wither/version/1.20-1.6.1-Fabric
